name: pv-experiments
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchdata
  - pytorch-cuda==11.7
  - datasets
  - huggingface_hub
  - xarray
  - zarr
  - numcodecs
  - cartopy
  - dask
  - fsspec
  - gcsfs
  - pip:
      - wandb
      - pseudo-labeller
      - metnet
      - einops
      - lightning
      - hydra-core
      - hydra-colorlog
      - hydra-optuna-sweeper
      - tensorboard