model_name: "irradiance_inference"
model:
  forecast_steps: 48
  lr: 1e-5
  input_channels: 19
  input_size: 16
  input_steps: 6
  latent_channels: 16
  conv3d_channels: 256
  hidden_dim: 16
  kernel_size: 3
  num_layers: 4
  output_steps: 48
  pv_meta_input_channels: 2
dataloader:
  config: "configs/datapipe/forecastor.yaml"
  sun: true
  nwp: true
  sat: true
  hrv: true
  topo: true
  size: 16
  size_meters: 256000
  use_meters: true
  use_future: false
  num_workers: 1
  batch: 1
epochs: 100
fp16: true
num_gpu: 0
cpu: false
accumulate: 1
wandb: false
