model_name: "irradiance"
model:
  forecast_steps: 37
  lr: 1e-5
  input_channels: 31
  input_size: 64
  input_steps: 7
  latent_channels: 8
  conv3d_channels: 512
  hidden_dim: 1024
  kernel_size: 3
  num_layers: 8
  output_steps: 37
  pv_meta_input_channels: 2
dataloader:
  config: "configs/datapipe/forecastor.yaml"
  sun: true
  nwp: true
  sat: true
  hrv: true
  topo: true
  size: 64
  size_meters: 256000
  use_meters: true
  use_future: false
  num_workers: 1
  batch: 8
epochs: 100
fp16: true
num_gpu: 0
cpu: false
accumulate: 1
wandb: false