model_name: "metnet"
model:
  forecast_steps: 360
  lr: 1e-4
  input_channels: 28
  input_size: 64
  center_crop_size: 8
  hidden_dim: 1024
  att_layers: 8
  weights: "/mnt/storage_ssd_4tb/artifacts/model-store0av:v27"
dataloader:
  config: "configs/datapipe/metnet_donatello.yaml"
  sun: false
  nwp: true
  sat: false
  hrv: false
  topo: false
  size: 64
  center_meter: 32_000
  context_meter: 512_000
  num_workers: 4
  batch: 16

epochs: 100
fp16: true
num_gpu: 0
cpu: false
accumulate: 1
wandb: false