general:
  description: Config for producing batches on OCF's on-premises hardware.
  name: metnet_pv_site
input_data:
  default_forecast_minutes: 0
  default_history_minutes: 30
  #---------------------- GSP -------------------
  gsp:
    gsp_zarr_path: /mnt/storage_ssd_4tb/train_data/pv_gsp.zarr
    history_minutes: 120
    forecast_minutes: 0 # 48 Hours
    log_level: "ERROR"

  #---------------------- NWP -------------------
  nwp:
    nwp_image_size_pixels_height: 128
    nwp_image_size_pixels_width: 128
    nwp_zarr_path: /mnt/leonardo/storage_c/UKV_intermediate_version_7.zarr
    forecast_minutes: 1800 # 30 hours
    history_minutes: 60

  #---------------------- PV ---------minutes=60----------
  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: /mnt/storage_ssd_4tb/data/train_data/ocf_formatted/v0/passiv.netcdf
        pv_metadata_filename: /mnt/storage_ssd_4tb/data/train_data/ocf_formatted/v0/system_metadata_OCF_ONLY.csv
      #- label: pvoutput.org
      #  pv_filename: /mnt/storage_ssd_4tb/metnet_train/PVOutput.org/UK_PV_timeseries_batch.nc
      #  pv_metadata_filename: /mnt/storage_ssd_4tb/metnet_train/PVOutput.org/UK_PV_metadata.csv
    get_center: false
    history_minutes: 150 # 30 timesteps + t0 (To match NWP sequence length)
    forecast_minutes: 2880 # 48 hours
    log_level: "INFO"

  #---------------------- Satellite -------------
  satellite:
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 48
    satellite_image_size_pixels_width: 96
    satellite_zarr_path: "gs://public-datasets-eumetsat-solar-forecasting/satellite/EUMETSAT/SEVIRI_RSS/v4/2020_nonhrv.zarr"
    keep_dawn_dusk_hours: 2

  #---------------------- HRVSatellite -------------
  hrvsatellite:
    hrvsatellite_channels:
      - HRV
    hrvsatellite_image_size_pixels_height: 128
    hrvsatellite_image_size_pixels_width: 256
    hrvsatellite_zarr_path: "gs://public-datasets-eumetsat-solar-forecasting/satellite/EUMETSAT/SEVIRI_RSS/v4/2020_hrv.zarr"

  # ------------------------- Topographic ----------------
  topographic:
    topographic_filename: /mnt/storage_ssd_4tb/data/train_data/europe_dem_1km_osgb.tif
    topographic_image_size_pixels_width: 300
    topographic_image_size_pixels_height: 300

output_data:
  filepath: /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v15
process:
  batch_size: 8
  seed: 1234
  upload_every_n_batches: 0 # Write directly to output_data.filepath, not to a temp directory.
  n_train_batches: 8000
  n_validation_batches: 0
  n_test_batches: 400
